import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className="wrap">
        <div className="container text-center">
              <h1 id="main">10초 완성 영어 이메일</h1>
          <p>
            영어 글쓰기 스트레스는 이제 그만~<br/>
            키워드만 던져주면 찰떡같이 알아듣고 <br/>
            완벽하게 완성해주는 영어 원어민 AI 비서<br/>
          </p>
          <div className="container text-center">
            <a href="#" className="btn btn-primary" role="button">무료로 시작하기</a>
          </div>
          <div className="video-box">
            <video autoPlay loop muted poster="src/img/main_example.png">
              {/* <source src="src/img/main_example.mp4" type="video/mp4"> */}
              텐세컨드앱 작동 예시. 한국어를 입력하고 버튼을 누르면 영어로 이메일을 자동완성해준다.
            </video>
          </div>
        </div>
        <div className="container text-center">
          <h2>마법처럼 완성되는 완벽한 영어 이메일</h2>
          <p>
            영어로 입력해도, 한글로 입력해도 문맥까지 파악 완료<br/>
            빠르고 정확한 AI 비서와 함께 영어 스트레스에서 해방!<br/>
          </p>
        </div>

        <div className="container text-center">
          <h2>아무말 대잔치도 멋진 비즈니스 이메일로!</h2>
          <p>
            생각나는대로 마구 적은 메시지도 비즈니스에 딱 맞는 이메일로
            업그레이드<br/>
            문법 오류 0% 전문성 100% 내맘까지 알아주는 전담 비서<br/>
          </p>
        </div>

        <div className="container text-center">
          <h2>맘에 들 때까지 고객 감동 서비스</h2>
          <p>
            영어 이메일에 2% 감성을 더하고 싶다면! <br/>
            더 전문적으로더 길고 멋지게더 친근감 있게<br/>
            더 짧고 간결하게기쁨을 가득 담아감사표현을 담아 다시 쓰게 해보세요<br/>
            무한 재생 가능, 편리한 직접 편집 기능까지!<br/>
          </p>
        </div>

        <div className="container text-center">
          <h2>보너스 기능 (Coming Soon)</h2>
          <p>
            이메일만 쓰고 살 순 없잖아요? <br/>
            인스타그램, 트위터, 페이스북 포스팅도 AI 비서와 함께라면 문제없어요<br/>
          </p>
        </div>
      </div>
    </main>      
    </>
  );
}

